---
title: "CA vs splicing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r set working directory}

# Change to directory of cloning
setwd("~/PanCancer_CentrosomeAmplification/Survival_analyses/")

```

```{r all cohorts}

require(ggplot2)
library(survival)
library(survminer)

TCGA_cohorts_table <- read.delim("../TCGA_cohorts.txt")
TCGA_cohorts <- TCGA_cohorts_table$Cohort

Final_Expression_table <- read.delim("../Calculate_CA20_scores/CA20_expression_table_TCGA_CA20allCohorts.txt")
Final_Expression_table$Sample <- substr(Final_Expression_table$Sample, 1, 12)
Final_Expression_table$Sample_ID <- rownames(Final_Expression_table)

pdf("Survival_plots.pdf", width = 6, height = 5)

Table_survival_results <- data.frame()

for(c in 1:length(TCGA_cohorts)) {

cohort_TCGA <- TCGA_cohorts[c]

Final_Expression_table_cohort <- Final_Expression_table[Final_Expression_table$Cohort %in% cohort_TCGA,]

# Clinical data
Clinical <- read.delim(paste("../Calculate_CA20_scores/Firebrowse_download/gdac.broadinstitute.org_", cohort_TCGA,".Merge_Clinical.Level_1.2016012800.0.0/", cohort_TCGA,".clin.merged.txt", sep=""), row.names = 1)
Clinical=as.data.frame(t(Clinical))
 
#rownames(Clinical)=paste(Clinical$patient.bcr_patient_barcode,".01",sep="")
rownames(Clinical)=Clinical$patient.bcr_patient_barcode
rownames(Clinical)=gsub("-", ".", rownames(Clinical))
  
rownames(Clinical) <- toupper(rownames(Clinical))
  
Final_clinical=Clinical[,c(grep("patient.days_to_death", colnames(Clinical)), grep("patient.days_to_last_followup", colnames(Clinical)), grep("patient.stage_event.pathologic_stage", colnames(Clinical)))]
  
Final_clinical$final_OS=as.character(Final_clinical$patient.days_to_death)
Final_clinical$final_OS_event=0
Final_clinical$final_OS_event[complete.cases(Final_clinical$patient.days_to_death)] <- 1
Final_clinical$final_OS[!complete.cases(Final_clinical$patient.days_to_death)] <- as.character(Final_clinical$patient.days_to_last_followup[!complete.cases(Final_clinical$patient.days_to_death)] )
Final_clinical$final_OS=as.numeric(Final_clinical$final_OS)
  
# merge clinical + CA20
Final_table <- merge(Final_clinical, Final_Expression_table_cohort, by.x=0, by.y=21, all.y = T)
rownames(Final_table)=Final_table$Sample_ID
Final_table$sample <- Final_table$Row.names
Final_table=Final_table[,-1]


# Survival analyses

Final_table_merged_tumor <- Final_table[Final_table$sample_type_detail %in% c("Primary Solid Tumor", "Primary Blood Derived Cancer") & complete.cases(Final_table$final_OS) & complete.cases(Final_table$final_OS_event),]
Final_table_merged_tumor$final_OS_years <- Final_table_merged_tumor$final_OS/365

Final_table_merged_tumor$CA20_group <- ifelse(Final_table_merged_tumor$CA20<=median(Final_table_merged_tumor$CA20), "Lower", "Higher")
Final_table_merged_tumor$CA20_group <- factor(Final_table_merged_tumor$CA20_group, levels = c("Lower", "Higher"))

Final_table_merged_tumor$SurvObj <- with(Final_table_merged_tumor, Surv(Final_table_merged_tumor$final_OS_years  , Final_table_merged_tumor$final_OS_event == 1))
km_cluster <- survfit(SurvObj ~ CA20_group, data = Final_table_merged_tumor)
surv_results=survdiff(SurvObj ~ CA20_group, data = Final_table_merged_tumor)
surv_results_p.value <- 1 - pchisq(surv_results$chisq, length(surv_results$n) - 1)

if(surv_results$obs[1] > surv_results$exp[1]) worst_median <- "Higher CA20"
if(surv_results$obs[2] > surv_results$exp[2]) worst_median <- "Lower CA20"

higher_median <- as.numeric(length(which(complete.cases(Final_table_merged_tumor$final_OS) & complete.cases(Final_table_merged_tumor$final_OS_event) & Final_table_merged_tumor$CA20_group %in% "Higher")))
lower_median <- as.numeric(length(which(complete.cases(Final_table_merged_tumor$final_OS) & complete.cases(Final_table_merged_tumor$final_OS_event) & Final_table_merged_tumor$CA20_group %in% "Lower")))

surv_summ <- summary(km_cluster,times=c(1,5))
Lower_surv5 <- ifelse(length(surv_summ$surv) > 2, surv_summ$surv[2], surv_summ$surv[1])
Higher_surv5 <- ifelse(length(surv_summ$surv) > 2, surv_summ$surv[4], surv_summ$surv[2])

# main plot
plot <- ggsurvplot(km_cluster, legend = "none", xlab="Years", font.main = 18,
   risk.table = TRUE, # absolute number and percentage at risk.
   risk.table.col = "strata", # Change risk table color by groups
   risk.table.fontsize = 4.5,
   font.x =  16,
   font.y = 16,
   font.tickslab = 14,
   xlim=c(0,10),
   break.time.by=2.5,
   palette = c("dodgerblue", "orangered"), pval = F)
plot$plot <- plot$plot +
  labs(title = cohort_TCGA) +
  theme(plot.title = element_text(hjust = 0.5))
plot$plot <- plot$plot +
  geom_segment(aes(x=5,xend=5,y=-0, yend=Lower_surv5), linetype=2, size=0.2) +
  geom_segment(aes(x=0,xend=5,y=Lower_surv5, yend=Lower_surv5), linetype=2, size=0.2) +
  geom_segment(aes(x=0,xend=5,y=Higher_surv5, yend=Higher_surv5), linetype=2, size=0.2) +
  geom_point(x = 5, y = Lower_surv5, fill="dodgerblue", colour="black", shape=21, size=3.5, stroke=0.3) +
  geom_point(x = 5, y = Higher_surv5, fill="orangered", colour="black", shape=21, size=3.5, stroke=0.3) +
  scale_x_continuous(breaks = seq(0,20,2.5))
plot$table <- plot$table + 
  theme(panel.border = element_rect(colour="black", fill=NA),
        plot.title = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank()
        )

# only plot significant ones
if(cohort_TCGA %in% c("ACC", "LGG", "BRCA", "LUAD", "PAAD", "KICH", "UVM")) print(plot)

if(cohort_TCGA %in% c("MESO")) print(plot + geom_point(x = 5, y = 0, fill="orangered", colour="black", shape=21, size=3.5, stroke=0.3))

### create table survival result

Table_survival_results_cohort <- data.frame(TCGA_cohort=cohort_TCGA,
                                            Sample_number= nrow(Final_table_merged_tumor[complete.cases(Final_table_merged_tumor$final_OS) & complete.cases(Final_table_merged_tumor$final_OS_event),]),
                                            Median_cutoff_pvalue=surv_results_p.value,
                                            Median_worst=worst_median
                                            )

Table_survival_results=rbind(Table_survival_results, Table_survival_results_cohort)

} # TCGA cohort

dev.off()

## multiple testing survival
Table_survival_results$FDR <- p.adjust(Table_survival_results$Median_cutoff_pvalue, method = "fdr")
out <- Table_survival_results[order(Table_survival_results$Median_cutoff_pvalue),c(1:3,5)]
names(out) <- c("Cohort",	"Sample number", "P-value",	"FDR-adjusted p-value")

write.table(out, "TCGA_survival_analyses_median_results.txt", sep="\t", row.names = F, quote=F)

```

